##
# package     Devops with Lando and Docker, by Anibal Sanchez @anibal_sanchez - Ubucon Europe 2018
# subpackage  Lando
#
# author      Extly, CB.
# copyright   Copyright (C) 2018 Extly, CB. All rights reserved.
# license     https://www.gnu.org/licenses/gpl-3.0.html GNU/GPL
# link        https://extly.com
##

name: devops-with-lando-and-docker

proxy:
  html:
    # Give me http://devops-with-lando-and-docker.lndo.site and https://devops-with-lando-and-docker.lndo.site
    - devops-with-lando-and-docker.lndo.site

services:
  html:
    # Use the latest version of apache.
    type: apache:2.2

    # Optionally specify a webroot if it is a subdirectory of the appRoot
    webroot: web

    overrides:
      services:
        ports:
          # A nice local site http://localhost:8080
          - '8080:80'

